{application,pizza_factory_locator,
             [{applications,[kernel,stdlib,elixir,logger,crypto,jason,
                             mongodb]},
              {description,"pizza_factory_locator"},
              {modules,['Elixir.Configuration','Elixir.Coordinates',
                        'Elixir.Database','Elixir.Factory','Elixir.Order',
                        'Elixir.PizzaFactoryLocator']},
              {registered,[]},
              {vsn,"0.1.0"}]}.
