{application,factory_locator,
             [{applications,[kernel,stdlib,elixir,logger,jason,mongodb]},
              {description,"factory_locator"},
              {modules,['Elixir.Configuration','Elixir.Coordinates',
                        'Elixir.Database','Elixir.FactoryLocator',
                        'Elixir.FactoryLocator.Application','Elixir.Order']},
              {registered,[]},
              {vsn,"0.1.0"},
              {mod,{'Elixir.FactoryLocator.Application',[]}}]}.
